#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Batch recompiles HoverRace track files using MazeCompiler.

.DESCRIPTION
    This script finds HoverCad-generated debug files in %TEMP% and uses them to
    recompile track files with the current ColorTab.pal palette.

    Process:
    1. Verifies MazeCompiler.exe exists
    2. Ensures ColorTab.pal is available
    3. Finds HC*.tmp.debug files from HoverCad in %TEMP%
    4. Runs MazeCompiler for each debug file
    5. Generates .trk files with embedded color palette

.EXAMPLE
    # From the Release directory where MazeCompiler.exe is located:
    .\compile_tracks.ps1

.NOTES
    Prerequisites:
    - MazeCompiler.exe must be in current directory
    - ColorTab.pal must be in current directory
    - HoverCad debug files must be in %TEMP% (generated by HoverCad Compile button)
#>

# Strict mode
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "====================================" -ForegroundColor Cyan
Write-Host " HoverRace Track Recompilation" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan
Write-Host ""

# Configuration
$currentDir = Get-Location
$mazeCompilerPath = Join-Path $currentDir "MazeCompiler.exe"
$colorTabPath = Join-Path $currentDir "ColorTab.pal"
$outputDir = Join-Path $currentDir "Tracks\mazes"
$tempDir = $env:TEMP

Write-Host "Current directory: $currentDir" -ForegroundColor Gray
Write-Host ""

# Validate MazeCompiler
if (-not (Test-Path $mazeCompilerPath)) {
    Write-Host "ERROR: MazeCompiler.exe not found" -ForegroundColor Red
    Write-Host "Expected at: $mazeCompilerPath" -ForegroundColor Red
    Write-Host ""
    Write-Host "Solution: Run this script from the directory containing MazeCompiler.exe" -ForegroundColor Yellow
    exit 1
}

Write-Host "✓ MazeCompiler found" -ForegroundColor Green

# Validate/Copy ColorTab.pal
if (-not (Test-Path $colorTabPath)) {
    Write-Host "⚠ ColorTab.pal not in current directory" -ForegroundColor Yellow
    
    $altPath = "..\NetTarget\bitmaps\ColorTab.pal"
    if (Test-Path $altPath) {
        Write-Host "  Found at: $altPath" -ForegroundColor Yellow
        Write-Host "  Copying to current directory..." -ForegroundColor Yellow
        Copy-Item $altPath $colorTabPath -Force
        Write-Host "  ✓ Copied" -ForegroundColor Green
    } else {
        Write-Host "ERROR: ColorTab.pal not found" -ForegroundColor Red
        Write-Host "Expected at: $colorTabPath" -ForegroundColor Red
        Write-Host "Or: $altPath" -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host "✓ ColorTab.pal verified" -ForegroundColor Green
}

Write-Host ""

# Ensure output directory exists
if (-not (Test-Path $outputDir)) {
    Write-Host "Creating output directory: $outputDir" -ForegroundColor Gray
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

Write-Host "Output directory: $outputDir" -ForegroundColor Gray
Write-Host ""

# Find HoverCad debug files
Write-Host "Searching for HoverCad debug files in: $tempDir" -ForegroundColor Gray
$debugFiles = Get-ChildItem -Path $tempDir -Filter "HC*.tmp.debug" -ErrorAction SilentlyContinue

if ($debugFiles.Count -eq 0) {
    Write-Host "No HoverCad debug files found" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "To generate debug files:" -ForegroundColor Yellow
    Write-Host "  1. Run HoverCad:" -ForegroundColor Gray
    Write-Host "     C:\originalhr\HoverRace\HoverCad\Release\HoverCad.exe" -ForegroundColor Cyan
    Write-Host "  2. Open a .TR track file from: " -ForegroundColor Gray
    Write-Host "     C:\originalhr\HoverRace\NetTarget\mazes\" -ForegroundColor Cyan
    Write-Host "  3. Click the 'Compile' button" -ForegroundColor Gray
    Write-Host "  4. Choose an output location for the .TRK file" -ForegroundColor Gray
    Write-Host "  5. After compilation completes, debug files will be in %TEMP%" -ForegroundColor Gray
    Write-Host "  6. Re-run this script" -ForegroundColor Gray
    Write-Host ""
    exit 0
}

Write-Host "Found $($debugFiles.Count) debug file(s)" -ForegroundColor Green
Write-Host ""

# Process each debug file
$successCount = 0
$failureCount = 0

foreach ($debugFile in $debugFiles) {
    $debugName = $debugFile.Name
    
    # Extract track name from debug filename
    # HC* format: HCA972.tmp.debug
    # Extract just the name part: A972
    $nameMatch = $debugName -match '^HC(.+?)\.tmp\.debug$'
    if (-not $nameMatch) {
        Write-Host "Skipping: $debugName (invalid format)" -ForegroundColor Yellow
        continue
    }
    
    # Create output filename from debug file
    # For now, use a generic name based on the debug file
    $trackName = "CompiledTrack_" + (Get-Date -Format "yyyyMMdd_HHmmss")
    $outputPath = Join-Path $outputDir "$trackName.trk"
    
    Write-Host "Processing: $debugName" -ForegroundColor Cyan
    
    # Copy debug file to temporary .txt file
    $txtFile = [System.IO.Path]::GetTempFileName()
    $txtFile = $txtFile -replace '\.tmp$', '.txt'
    
    try {
        Copy-Item $debugFile.FullName $txtFile -Force | Out-Null
        
        Write-Host "  Compiling to: $trackName.trk" -ForegroundColor Gray
        
        # Run MazeCompiler
        $process = Start-Process -FilePath $mazeCompilerPath `
                                 -ArgumentList "`"$outputPath`"", "`"$txtFile`"" `
                                 -NoNewWindow `
                                 -Wait `
                                 -PassThru
        
        if ($process.ExitCode -eq 0) {
            Write-Host "  ✓ Compiled successfully" -ForegroundColor Green
            $successCount++
            
            # Show file info
            $fileInfo = Get-Item $outputPath
            Write-Host "    Size: $([Math]::Round($fileInfo.Length / 1KB)) KB" -ForegroundColor Gray
        } else {
            Write-Host "  ✗ Compilation failed (exit code: $($process.ExitCode))" -ForegroundColor Red
            $failureCount++
        }
    } catch {
        Write-Host "  ✗ Error: $_" -ForegroundColor Red
        $failureCount++
    } finally {
        # Clean up temporary file
        if (Test-Path $txtFile) {
            Remove-Item $txtFile -Force -ErrorAction SilentlyContinue | Out-Null
        }
    }
    
    Write-Host ""
}

# Summary
Write-Host "====================================" -ForegroundColor Cyan
Write-Host " Recompilation Summary" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan

if ($successCount -gt 0) {
    Write-Host "✓ Successfully compiled: $successCount" -ForegroundColor Green
}
if ($failureCount -gt 0) {
    Write-Host "✗ Failed to compile: $failureCount" -ForegroundColor Red
}

Write-Host ""
Write-Host "Output directory: $outputDir" -ForegroundColor Gray
Write-Host ""
Write-Host "Next step: Test Game2.exe with the recompiled tracks" -ForegroundColor Cyan
